# Generated by Django 5.0.6 on 2024-07-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
