# Generated by Django 5.0.6 on 2024-06-28 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_branch_options_alter_commentary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='commentary',
            name='rating',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='forum.rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='forum.rating'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='forum.rating')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ('-time_create',),
                'indexes': [models.Index(fields=['-time_create', 'value'], name='forum_grade_time_cr_191c03_idx')],
                'unique_together': {('rating', 'user')},
            },
        ),
    ]
