# Generated by Django 5.0.6 on 2024-06-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rating_commentary_rating_post_rating_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='forum.rating'),
        ),
    ]
